# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb1654eba220eca9950902a786ab5b574dfcb7814457ccfb8f1c6da8af8410c4564ca4321243542a572260e805c8dee8076778a0288b99118779094a28f1da78

test:
  secret_key_base: bc72fadfc8ea35df78204fdf28bf9b3c21a2cd194d16adc4e795716db973ce1d9b659b16d88f8275937dcf4e6898b09b5c58cc0ce0416a6d720e8f7e1155da40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
